About Me Project Parts 1-3
yen1027/CodeBusters pull request #5
Opened 2019-02-25 04:02 UTC by eyobtefera

This is the about me project parts 1-3.

2019-02-25 04:26 UTC, eyobtefera commented
Part 4 of the about me section

2019-02-25 17:02 UTC, nsallembiencodeu requested changes
The changes to the main code look fine, however there are a lot of superfluous files which make it difficult to review the change. Would you be able to remove them from the PR?

2019-02-25 17:02 UTC, nsallembiencodeu commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
It's probably OK to remove the .classpath, .settings/..., .project, etc. files which are Eclipse specific from the repo. The idea here is that everyone should be able to use whatever editor they want (Eclipse, IntelliJ, VIM, Emacs, ...) and that the files that contain configuration for the editor should be be in the repo, but stay on your local working directory.

2019-02-25 19:45 UTC, eyobtefera commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Okay, my problem was without those changes nothing would work locally so I figured that they were necessary to commit. From now on I will not including those changes. Thank you for your feedback.

2019-03-15 20:42 UTC, closed without merging

2019-03-15 20:42 UTC, nsallembiencodeu commented
Submitted the other PR which had the same changes